export const EXPORT_REPORT = 'exportReport'
export const EXPORT_REPORT_WITHDRAW = 'exportReportWithdraw'
export const FETCH_GUARANTEED_ACCOUNT = 'fetchGuaranteedAccount'

export const FETCH_ACCOUNTS = 'getAccount'
export const FETCH_ACCOUNTS_POPUP = 'getAccountPopup'
export const FETCH_ACCOUNTS_TOTAL = 'getAccountsTotal'
export const CREATE_FILE_ACCOUNT = 'createFileAccount'

export const HOLD_BALANCE = 'holdBalance'
export const UN_HOLD_BALANCE = 'unHoldBalance'

export const FETCH_REQUEST = 'fetchRequest'
export const FETCH_REQUEST_TOTAL = 'fetchRequestTotal'

export const FETCH_TRANSACTION_HISTORY = 'fetchTransactionHistory'
export const FETCH_TRANSACTION_HISTORY_TOTAL = 'fetchTransactionHistoryTotal'

export const FETCH_TRANSACTION_WITHDRAW = 'fetchTransactionWithdraw'
export const FETCH_TRANSACTION_WITHDRAW_TOTAL = 'fetchTransactionWithdrawTotal'
export const INIT_BATCH_PAYMENT = 'initBatchPayment'
export const INIT_RETRY_BATCH_PAYMENT = 'initRetryBatchPayment'
export const GET_BATCH_INFO = 'getBatchInfo'
export const CLEAR_TRANSACTION_WITHDRAW_DATA = 'clearTransactionWithdrawData'
export const FETCH_TRANS_TYPE = 'fetchTransType'
export const CREATE_TRANS_TYPE = 'createTransType'
export const UPDATE_TRANS_TYPE = 'updateTransType'

export const FETCH_WITHDRAW_CONFIG_LIST = 'fetchWithdrawConfigList'
export const FETCH_WITHDRAW_CONFIG_TOTAL = 'fetchWithdrawConfigTotal'
export const CLEAR_WITHDRAW_CONFIG_LIST = 'clearWithdrawConfigList'

export const CREATE_MANUAL_TRANSACTION = 'createManualTransaction'
export const CREATE_FILE_TRANSACTION = 'createFileTransaction'
export const DOWNLOAD_FILE_EXPORT = 'downloadFileExport'
export const DOWNLOAD_FILE_AR = 'downloadFileAR'
export const DOWNLOAD_FILE_TRANSACTION = 'downloadFileTransaction'
export const DOWNLOAD_FILE_WITH_NAME = 'downloadFileWithName'
export const SETUP_ACCOUNT = 'setupAccount'

export const FETCH_HOLIDAY = 'fetchHoliday'
export const CREATE_HOLIDAY = 'createHoliday'
export const DELETE_HOLIDAY = 'deleteHoliday'

export const CREATE_WALLET = 'createWallet'
export const CHECK_KYC = 'checkKyc'
export const CREATE_WALLET_COMPARTMENT = 'createWalletCompartment'
export const UPDATE_USER_MOBILE = 'updateUserMobile'
export const UPDATE_USER_EKYC = 'updateUserEkyc'

export const FETCH_BANKS = 'fetchBanks'
export const FETCH_SOURCE_BANKS = 'fetchSourceBanks'
export const FETCH_BANK_CHANNELS = 'fetchBankChannels'
export const UPDATE_LINK_NOTE = 'updateLinkNote'
export const UPDATE_SUPPORT_BANK = 'updateSupportBank'

export const FETCH_PERMISSION = 'fetchPermission'

export const UPDATE_EXCEL_SUCCESS = 'updateExcelSuccess'
export const UPDATE_EXCEL_FAIL = 'updateExcelFail'
export const PUSH_TO_EXCEL = 'pushToExcel'

export const CREATE_CONFIG = 'createConfig'
export const DELETE_CONFIG = 'deleteConfig'
export const RELOAD_CONFIG_MERCHANT = 'reloadConfigMerchant'
export const RELOAD_CONFIG_FINANCE = 'reloadConfigFinance'
export const RELOAD_CONFIG_GATEWAY = 'reloadConfigGateway'

export const DOWNLOAD_FILE_ECOM = 'downloadFileEcom'

export const DOWNLOAD_VPBANK_FILE = 'downloadVpbankFile'

export const CLEAR_TRANSFER_BANK_DATA = 'clearTransferBankData'
export const FETCH_TRANSFER_BANK_LIST = 'fetchTransferBankList'

export const CLEAR_TRANSFER_BANK_PENDING_LOG = 'clearTransferBankPendingLog'
export const FETCH_TRANSFER_BANK_PENDING_LOG = 'fetchTransferBankPendingLog'
export const UPDATE_BANK_TRANSFER_STATUS = 'UPDATE_BANK_TRANSFER_STATUS'
export const UPDATE_TRANSFER_BANK_PENDING_STATUS = 'UPDATE_TRANSFER_BANK_PENDING_STATUS'
export const PUSH_TO_BANK_PAYMENT = 'PUSH_TO_BANK_PAYMENT'
export const CREATE_BANK_TRANSACTION = 'createBankTransaction'
export const CREATE_RECONCILE_BANK_TRANSACTION = 'createReconcileBankTransaction'
export const CREATE_RECONCILE_BANK = 'createReconcileBank'
export const DEBTS_COLLECT = 'DEBTS_COLLECT'

export const CREATE_FILE_NAPAS_TRANSACTION = 'createFileNapasTransaction'
export const FETCH_PARTNERS = 'fetchPartners'
export const FETCH_PARTNER_BY_UTILITY_CODE = 'fetchPartnerByUtilityCode'
export const FETCH_PARTNER_PRODUCTS = 'fetchPartnerProducts'
export const FETCH_PARTNER_PRODUCT_DETAIL = 'fetchPartnerProductDetail'
export const CREATE_PARTNER_PRODUCT = 'createPartnerProduct'
export const UPDATE_PARTNER_PRODUCT = 'updatePartnerProduct'
export const DELETE_PARTNER_PRODUCT = 'deletePartnerProduct'

export const FETCH_PARTNER_CONFIGS = 'fetchPartnerConfigs'
export const FETCH_PARTNER_CONFIG_DETAIL = 'fetchPartnerConfigDetail'
export const CREATE_PARTNER_CONFIG = 'createPartnerConfig'
export const UPDATE_PARTNER_CONFIG = 'updatePartnerConfig'
export const DELETE_PARTNER_CONFIG = 'deletePartnerConfig'

export const FETCH_PROVIDERS = 'fetchProviders'
export const CREATE_PROVIDER = 'createProvider'
export const UPDATE_PROVIDER = 'updateProvider'
export const DELETE_PROVIDER = 'deleteProvider'

export const FETCH_INVOICES = 'fetchInvoices'
export const FETCH_INVOICE_COUNT = 'fetchInvoiceCount'
export const FETCH_INVOICE_PDF = 'fetchInvoicePdf'
export const FETCH_INVOICE_DETAIL = 'fetchInvoiceDetail'

export const FETCH_BILL_AR = 'fetchBillAR'
export const FETCH_SHOP_VAT_INFO = 'fetchShopVatInfo'
export const AUTO_EXPORT_BILL_AR = 'autoExportBillAr'
export const EXPORT_ALL_BILL_AR = 'exportAllBillAr'
export const RESET_BILL = 'resetBill'
export const FETCH_EXPORT_AR = 'fetchExportAr'
export const SEND_INVOICE_DATA = 'sendInvoiceData'
export const EXPORT_INVOICE_EXCEL = 'exportInvoiceExcel'

export const FETCH_PROMOTIONS = 'fetchPromotions'
export const CREATE_PROMOTION = 'createPromotion'
export const UPDATE_PROMOTION = 'updatePromotion'
export const DELETE_PROMOTION = 'deletePromotion'

export const FETCH_BLOCK_DEVICE = 'fetchBlockDevice'
export const CREATE_BLOCK_DEVICE = 'createBlockDevice'
export const UPDATE_BLOCK_DEVICE = 'updateBlockDevice'
export const FETCH_SHOP_DEBT_PAYOFF = 'fetchShopDebtPayoff'
export const EXPORT_SHOP_DEBT_PAYOFF = 'exportShopDebtPayoff'

export const FETCH_BLOCK_SOTP = 'fetchBlockSotp'
export const UPDATE_BLOCK_SOTP = 'updateBlockSotp'
export const FETCH_TRANSFER_BANK_CONFIG = 'fetchTransferBankConfig'
export const CREATE_TRANSFER_BANK_CONFIG = 'createTransferBankConfig'
export const UPDATE_TRANSFER_BANK_CONFIG = 'updateTransferBankConfig'
export const DELETE_TRANSFER_BANK_CONFIG = 'deleteTransferBankConfig'
export const CREATE_SUB_ACCOUNT = 'createSubAccount'
export const FETCH_USER_SUB_LIST = 'fetchUserSubList'
export const FETCH_COD_INFO = 'fetchCodInfo'
export const FETCH_COD_VA_TRANS = 'fetchCodVATrans'
export const CREATE_REQUEST_COD_VA_TRANS = 'createRequestCodVATrans'
export const FETCH_VA_TRANSFER_REQUESTS = 'fetchVATransferRequests'
export const APPROVE_VA_TRANSFER_REQUESTS = 'approveVATransferRequests'
export const DELETE_VA_TRANSFER_REQUEST = 'deleteVATransferRequest'
export const APPROVE_REF_VA_TRANSFER_REQUEST = "approveRefVATransferRequest"
export const CHECK_INFO_BANK_COD = 'checkInfoBankCod'
export const EXPORT_VA_TRANSFER_REQUEST_EXCEL = 'exportVATransferRequestExcel'
