export const EXPORT_REPORT = 'exportReport'

export const FETCH_ACCOUNTS = 'getAccount'
export const FETCH_ACCOUNTS_POPUP = 'getAccountPopup'
export const FETCH_ACCOUNTS_TOTAL = 'getAccountsTotal'
export const CREATE_FILE_ACCOUNT = 'createFileAccount'

export const HOLD_BALANCE = 'holdBalance'
export const UN_HOLD_BALANCE = 'unHoldBalance'
export const CREATE_FILE_TRANSACTION = 'createFileTransaction'
export const DOWNLOAD_FILE_EXPORT = 'downloadFileExport'
export const DOWNLOAD_FILE_AR = 'downloadFileAR'
export const DOWNLOAD_FILE_WITH_NAME = 'downloadFileWithName'
export const SETUP_ACCOUNT = 'setupAccount'
export const CREATE_WALLET_COMPARTMENT = 'createWalletCompartment'
export const CREATE_TEACHER_COMPARTMENT = 'createTeacherCompartment'

export const FETCH_PERMISSION = 'fetchPermission'
export const CREATE_SUB_ACCOUNT = 'createSubAccount'
export const FETCH_TEACHERS = 'getTeacher'
