export const SET_ACCOUNTS = 'setAccount'
export const SET_ACCOUNTS_TOTAL = 'setAccountTotal'

export const SET_TEACHERS = 'setTeacher'
export const SET_GROUP_TEACHERS = 'setGroupTeacher'
export const SET_ALL_GROUP_TEACHERS = 'setAllGroupTeacher'
export const SET_GROUP_TEACHER_DETAIL = 'setGroupTeacherDetail'
export const SET_CLASSES = 'setClass'
export const SET_STUDENT_PROJECTS = 'setStudentProject'
export const SET_SUBJECTS = 'setSubject'
